version: '3.9'
services:
  front:
    image: sermalenk/skypro-front:lesson-35
    container_name: front
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./frontend/docker/:/etc/nginx/

  api:
    image: vitaliimadiakin/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    container_name: api
    volumes:
      - ./static:/app/static
    ports:
      - '8000:8000'
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    image: vitaliimadiakin/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    container_name: migrations
    depends_on:
      pg:
        condition: service_healthy
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate"

  pg:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5