name: Build and deploy workflow
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: set docker tag
        run: echo "DOCKER_TAG=$(basename $GITHUB_REF)-${GITHUB_RUN_ID}" >> $GITHUB_ENV
      - name: print files
        run: ls -la
      - name: docker build
        run: docker build -t vitaliimadiakin/todolist:${{ env.DOCKER_TAG }} .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push vitaliimadiakin/todolist:${{ env.DOCKER_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render config
        run: |
          mkdir skypro
          cat docker-compose-ci.yaml | envsubst > docker-compose.yaml
      - name: clone files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "docker-compose.yaml,nginx.conf"
          target: "todolist_app"
          strip-components: 1
      - name: run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd todolist_app
            docker-compose up -d
