name: Build and deploy workflow
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DEBUG: ${{ secrets.DEBUG }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      VK_OAUTH2_KEY: ${{ secrets.VK_OAUTH2_KEY }}
      VK_OAUTH2_SECRET: ${{ secrets.VK_OAUTH2_SECRET }}
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render .env
        run: |
          cp .env.example .env.temp
          sed -e 's/\${\(.*\)}/\$\1/g' .env.temp | envsubst > .env
          rm .env.temp
      - name: print files
        run: ls -la
      - name: docker build
        run: |
          BRANCH_NAME=$(basename $GITHUB_REF)
          DOCKER_TAG="${BRANCH_NAME}-${GITHUB_RUN_ID}"
          docker build -t vitaliimadiakin/todolist:$DOCKER_TAG .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: |
          BRANCH_NAME=$(basename $GITHUB_REF)
          DOCKER_TAG="${BRANCH_NAME}-${GITHUB_RUN_ID}"
          docker push vitaliimadiakin/todolist:$DOCKER_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DEBUG: ${{ secrets.DEBUG }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      VK_OAUTH2_KEY: ${{ secrets.VK_OAUTH2_KEY }}
      VK_OAUTH2_SECRET: ${{ secrets.VK_OAUTH2_SECRET }}
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render config
        run: |
          mkdir skypro
          cat docker-compose-ci.yaml | envsubst > docker-compose.yaml
      - name: clone files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "docker-compose.yaml,nginx.conf"
          target: "todolist_app"
          strip-components: 1
      - name: run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd todolist_app
            docker-compose up -d
